//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 200.146773 on Stable branch
// Generated with ALiVE version 1.12.1.2002131
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class TAMSF_VSC_I {
        displayName = "Valice Security Company";
        side = 2;
        flag = "\a3\Data_F_Exp\Flags\flag_CTRG_CO.paa";
        icon = "\a3\Data_F_Exp\Flags\flag_CTRG_CO.paa";
        priority = 0;
    };
};