//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 200.146773 on Stable branch
// Generated with ALiVE version 1.12.1.2002131
//////////////////////////////////////////////////////////////////////////////////


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class I_soldier_F;
    class I_soldier_F_OCimport_01 : I_soldier_F { scope = 0; class EventHandlers; };
    class I_soldier_F_OCimport_02 : I_soldier_F_OCimport_01 { class EventHandlers; };

    class I_Soldier_LAT_F;
    class I_Soldier_LAT_F_OCimport_01 : I_Soldier_LAT_F { scope = 0; class EventHandlers; };
    class I_Soldier_LAT_F_OCimport_02 : I_Soldier_LAT_F_OCimport_01 { class EventHandlers; };

    class I_Soldier_AT_F;
    class I_Soldier_AT_F_OCimport_01 : I_Soldier_AT_F { scope = 0; class EventHandlers; };
    class I_Soldier_AT_F_OCimport_02 : I_Soldier_AT_F_OCimport_01 { class EventHandlers; };

    class I_Soldier_GL_F;
    class I_Soldier_GL_F_OCimport_01 : I_Soldier_GL_F { scope = 0; class EventHandlers; };
    class I_Soldier_GL_F_OCimport_02 : I_Soldier_GL_F_OCimport_01 { class EventHandlers; };

    class I_Soldier_M_F;
    class I_Soldier_M_F_OCimport_01 : I_Soldier_M_F { scope = 0; class EventHandlers; };
    class I_Soldier_M_F_OCimport_02 : I_Soldier_M_F_OCimport_01 { class EventHandlers; };

    class I_medic_F;
    class I_medic_F_OCimport_01 : I_medic_F { scope = 0; class EventHandlers; };
    class I_medic_F_OCimport_02 : I_medic_F_OCimport_01 { class EventHandlers; };

    class I_Soldier_TL_F;
    class I_Soldier_TL_F_OCimport_01 : I_Soldier_TL_F { scope = 0; class EventHandlers; };
    class I_Soldier_TL_F_OCimport_02 : I_Soldier_TL_F_OCimport_01 { class EventHandlers; };

    class UK3CB_ADA_I_SUV_Armed;
    class UK3CB_ADA_I_SUV_Armed_OCimport_01 : UK3CB_ADA_I_SUV_Armed { scope = 0; class EventHandlers; class Turrets; };
    class UK3CB_ADA_I_SUV_Armed_OCimport_02 : UK3CB_ADA_I_SUV_Armed_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class GunnerTurret;
        };
    };

    class UK3CB_ADC_I_SUV_Armoured;
    class UK3CB_ADC_I_SUV_Armoured_OCimport_01 : UK3CB_ADC_I_SUV_Armoured { scope = 0; class EventHandlers; };
    class UK3CB_ADC_I_SUV_Armoured_OCimport_02 : UK3CB_ADC_I_SUV_Armoured_OCimport_01 { scope = 0; class EventHandlers; };

    class UK3CB_UN_I_UH1H_M240;
    class UK3CB_UN_I_UH1H_M240_OCimport_01 : UK3CB_UN_I_UH1H_M240 { scope = 0; class EventHandlers; class Turrets; };
    class UK3CB_UN_I_UH1H_M240_OCimport_02 : UK3CB_UN_I_UH1H_M240_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class RightGunner;
            class LeftGunner;
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };


    class TAMSF_VSC_Operator : I_soldier_F_OCimport_02 {
        editorPreview = \x\\addons\tamsfvsci\data\preview\TAMSF_VSC_Operator.JPG;
        author = "MSG D.North";
        scope = 2;
        scopeCurator = 2;
        displayName = "Operator";
        side = 2;
        faction = "TAMSF_VSC_I";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_HAF_default"};

        uniformClass = "U_B_CTRG_Soldier_3_F";

        linkedItems[] = {"V_PlateCarrier1_rgr_noflag_F","H_HelmetSpecB","ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_PlateCarrier1_rgr_noflag_F","H_HelmetSpecB","ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch"};

        weapons[] = {"hlc_rifle_416D10_st6","hlc_pistol_P229R_Combat","ACE_Vector"};
        respawnWeapons[] = {"hlc_rifle_416D10_st6","hlc_pistol_P229R_Combat","ACE_Vector"};

        magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger","hlc_13Rnd_9x19_JHP_P228","rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger","hlc_13Rnd_9x19_JHP_P228"};
        respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger","hlc_13Rnd_9x19_JHP_P228","rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger","hlc_13Rnd_9x19_JHP_P228"};

        ALiVE_orbatCreator_loadout[] = {{"hlc_rifle_416D10_st6","hlc_muzzle_556NATO_rotexiiic_grey","rhsusf_acc_anpeq15side_bk","rhsusf_acc_g33_T1",{"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger",30},{},""},{},{"hlc_pistol_P229R_Combat","","","HLC_optic228_VTAC",{"hlc_13Rnd_9x19_JHP_P228",13},{},""},{"U_B_CTRG_Soldier_3_F",{{"ACE_EarPlugs",1},{"ACE_Flashlight_XL50",1},{"ACE_CableTie",5},{"ACE_tourniquet",2}}},{"V_PlateCarrier1_rgr_noflag_F",{{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",20},{"USP_GPNVG18",1},{"ACE_microDAGR",1},{"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger",8,30},{"hlc_13Rnd_9x19_JHP_P228",1,13},{"SmokeShell",1,1}}},{},"H_HelmetSpecB","rhs_googles_clear",{"ACE_Vector","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class TAMSF_VSC_Operator_LAT : I_Soldier_LAT_F_OCimport_02 {
        editorPreview = \x\\addons\tamsfvsci\data\preview\TAMSF_VSC_Operator_LAT.JPG;
        author = "MSG D.North";
        scope = 2;
        scopeCurator = 2;
        displayName = "Operator (AT)";
        side = 2;
        faction = "TAMSF_VSC_I";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_HAF_default"};

        uniformClass = "U_B_CTRG_Soldier_3_F";

        linkedItems[] = {"V_PlateCarrier1_rgr_noflag_F","H_HelmetSpecB","ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_PlateCarrier1_rgr_noflag_F","H_HelmetSpecB","ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch"};

        weapons[] = {"hlc_rifle_416D10_st6","rhs_weap_M136_hedp","hlc_pistol_P229R_Combat","ACE_Vector"};
        respawnWeapons[] = {"hlc_rifle_416D10_st6","rhs_weap_M136_hedp","hlc_pistol_P229R_Combat","ACE_Vector"};

        magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger","hlc_13Rnd_9x19_JHP_P228","rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger","hlc_13Rnd_9x19_JHP_P228"};
        respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger","hlc_13Rnd_9x19_JHP_P228","rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger","hlc_13Rnd_9x19_JHP_P228"};

        ALiVE_orbatCreator_loadout[] = {{"hlc_rifle_416D10_st6","hlc_muzzle_556NATO_rotexiiic_grey","rhsusf_acc_anpeq15side_bk","rhsusf_acc_g33_T1",{"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger",30},{},""},{"rhs_weap_M136_hedp","","","",{},{},""},{"hlc_pistol_P229R_Combat","","","HLC_optic228_VTAC",{"hlc_13Rnd_9x19_JHP_P228",13},{},""},{"U_B_CTRG_Soldier_3_F",{{"ACE_EarPlugs",1},{"ACE_Flashlight_XL50",1},{"ACE_CableTie",5},{"ACE_tourniquet",2}}},{"V_PlateCarrier1_rgr_noflag_F",{{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",20},{"USP_GPNVG18",1},{"ACE_microDAGR",1},{"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger",8,30},{"hlc_13Rnd_9x19_JHP_P228",1,13},{"SmokeShell",1,1}}},{},"H_HelmetSpecB","rhs_googles_clear",{"ACE_Vector","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class TAMSF_VSC_ATOperator : I_Soldier_AT_F_OCimport_02 {
        editorPreview = \x\\addons\tamsfvsci\data\preview\TAMSF_VSC_ATOperator.JPG;
        author = "MSG D.North";
        scope = 2;
        scopeCurator = 2;
        displayName = "AT Operator";
        side = 2;
        faction = "TAMSF_VSC_I";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_HAF_default"};

        uniformClass = "U_B_CTRG_Soldier_3_F";

        linkedItems[] = {"V_PlateCarrier1_rgr_noflag_F","H_HelmetSpecB","ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_PlateCarrier1_rgr_noflag_F","H_HelmetSpecB","ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch"};

        weapons[] = {"hlc_rifle_416D10_st6","rhs_weap_maaws","hlc_pistol_P229R_Combat","ACE_Vector"};
        respawnWeapons[] = {"hlc_rifle_416D10_st6","rhs_weap_maaws","hlc_pistol_P229R_Combat","ACE_Vector"};

        magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger","rhs_mag_maaws_HEAT","hlc_13Rnd_9x19_JHP_P228","rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger","hlc_13Rnd_9x19_JHP_P228"};
        respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger","rhs_mag_maaws_HEAT","hlc_13Rnd_9x19_JHP_P228","rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger","hlc_13Rnd_9x19_JHP_P228"};

        backpack = "B_AssaultPack_rgr";

        ALiVE_orbatCreator_loadout[] = {{"hlc_rifle_416D10_st6","hlc_muzzle_556NATO_rotexiiic_grey","rhsusf_acc_anpeq15side_bk","rhsusf_acc_g33_T1",{"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger",30},{},""},{"rhs_weap_maaws","","","rhs_optic_maaws",{"rhs_mag_maaws_HEAT",1},{},""},{"hlc_pistol_P229R_Combat","","","HLC_optic228_VTAC",{"hlc_13Rnd_9x19_JHP_P228",13},{},""},{"U_B_CTRG_Soldier_3_F",{{"ACE_EarPlugs",1},{"ACE_Flashlight_XL50",1},{"ACE_CableTie",5},{"ACE_tourniquet",2}}},{"V_PlateCarrier1_rgr_noflag_F",{{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",20},{"USP_GPNVG18",1},{"ACE_microDAGR",1},{"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger",8,30},{"hlc_13Rnd_9x19_JHP_P228",1,13},{"SmokeShell",1,1}}},{"B_AssaultPack_rgr",{{"rhs_mag_maaws_HEDP",2,1}}},"H_HelmetSpecB","rhs_googles_clear",{"ACE_Vector","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class TAMSF_VSC_Grenadier : I_Soldier_GL_F_OCimport_02 {
        editorPreview = \x\\addons\tamsfvsci\data\preview\TAMSF_VSC_Grenadier.JPG;
        author = "MSG D.North";
        scope = 2;
        scopeCurator = 2;
        displayName = "Grenadier";
        side = 2;
        faction = "TAMSF_VSC_I";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_HAF_default"};

        uniformClass = "U_B_CTRG_Soldier_3_F";

        linkedItems[] = {"V_PlateCarrier1_rgr_noflag_F","H_HelmetSpecB","ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_PlateCarrier1_rgr_noflag_F","H_HelmetSpecB","ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch"};

        weapons[] = {"hlc_rifle_416D10_gl","hlc_pistol_P229R_Combat","ACE_Vector"};
        respawnWeapons[] = {"hlc_rifle_416D10_gl","hlc_pistol_P229R_Combat","ACE_Vector"};

        magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger","hlc_13Rnd_9x19_JHP_P228","rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger","hlc_13Rnd_9x19_JHP_P228"};
        respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger","hlc_13Rnd_9x19_JHP_P228","rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger","hlc_13Rnd_9x19_JHP_P228"};

        backpack = "B_AssaultPack_rgr";

        ALiVE_orbatCreator_loadout[] = {{"hlc_rifle_416D10_gl","hlc_muzzle_556NATO_rotexiiic_grey","rhsusf_acc_anpeq15side_bk","rhsusf_acc_g33_T1",{"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger",30},{},""},{},{"hlc_pistol_P229R_Combat","","","HLC_optic228_VTAC",{"hlc_13Rnd_9x19_JHP_P228",13},{},""},{"U_B_CTRG_Soldier_3_F",{{"ACE_EarPlugs",1},{"ACE_Flashlight_XL50",1},{"ACE_CableTie",5},{"ACE_tourniquet",2}}},{"V_PlateCarrier1_rgr_noflag_F",{{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",20},{"USP_GPNVG18",1},{"ACE_microDAGR",1},{"hlc_13Rnd_9x19_JHP_P228",1,13},{"SmokeShell",2,1},{"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger",7,30}}},{"B_AssaultPack_rgr",{{"1Rnd_HE_Grenade_shell",8,1},{"UGL_FlareCIR_F",2,1}}},"H_HelmetSpecB","rhs_googles_clear",{"ACE_Vector","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class TAMSF_VSC_Marksman : I_Soldier_M_F_OCimport_02 {
        editorPreview = \x\\addons\tamsfvsci\data\preview\TAMSF_VSC_Marksman.JPG;
        author = "MSG D.North";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marksman";
        side = 2;
        faction = "TAMSF_VSC_I";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_HAF_default"};

        uniformClass = "U_B_CTRG_Soldier_3_F";

        linkedItems[] = {"V_PlateCarrier1_rgr_noflag_F","H_HelmetSpecB","ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_PlateCarrier1_rgr_noflag_F","H_HelmetSpecB","ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch"};

        weapons[] = {"arifle_SPAR_03_blk_F","hlc_pistol_P229R_Combat","ACE_Vector"};
        respawnWeapons[] = {"arifle_SPAR_03_blk_F","hlc_pistol_P229R_Combat","ACE_Vector"};

        magazines[] = {"ACE_20Rnd_762x51_Mk316_Mod_0_Mag","hlc_13Rnd_9x19_JHP_P228","ACE_20Rnd_762x51_Mk316_Mod_0_Mag","hlc_13Rnd_9x19_JHP_P228"};
        respawnMagazines[] = {"ACE_20Rnd_762x51_Mk316_Mod_0_Mag","hlc_13Rnd_9x19_JHP_P228","ACE_20Rnd_762x51_Mk316_Mod_0_Mag","hlc_13Rnd_9x19_JHP_P228"};

        ALiVE_orbatCreator_loadout[] = {{"arifle_SPAR_03_blk_F","rhsgref_sdn6_suppressor","rhsusf_acc_anpeq15side_bk","rhsusf_acc_su230a_mrds",{"ACE_20Rnd_762x51_Mk316_Mod_0_Mag",20},{},""},{},{"hlc_pistol_P229R_Combat","","","HLC_optic228_VTAC",{"hlc_13Rnd_9x19_JHP_P228",13},{},""},{"U_B_CTRG_Soldier_3_F",{{"ACE_EarPlugs",1},{"ACE_Flashlight_XL50",1},{"ACE_CableTie",5},{"ACE_tourniquet",2}}},{"V_PlateCarrier1_rgr_noflag_F",{{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",20},{"USP_GPNVG18",1},{"ACE_microDAGR",1},{"hlc_13Rnd_9x19_JHP_P228",1,13},{"SmokeShell",1,1},{"ACE_20Rnd_762x51_Mk316_Mod_0_Mag",6,20}}},{},"H_HelmetSpecB","rhs_googles_clear",{"ACE_Vector","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class TAMSF_VSC_Medic : I_medic_F_OCimport_02 {
        editorPreview = \x\\addons\tamsfvsci\data\preview\TAMSF_VSC_Medic.JPG;
        author = "MSG D.North";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic";
        side = 2;
        faction = "TAMSF_VSC_I";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_HAF_default"};

        uniformClass = "U_B_CTRG_Soldier_3_F";

        linkedItems[] = {"V_PlateCarrier1_rgr_noflag_F","H_HelmetSpecB","ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_PlateCarrier1_rgr_noflag_F","H_HelmetSpecB","ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch"};

        weapons[] = {"hlc_rifle_416D10_st6","hlc_pistol_P229R_Combat","ACE_Vector"};
        respawnWeapons[] = {"hlc_rifle_416D10_st6","hlc_pistol_P229R_Combat","ACE_Vector"};

        magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger","hlc_13Rnd_9x19_JHP_P228","rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger","hlc_13Rnd_9x19_JHP_P228"};
        respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger","hlc_13Rnd_9x19_JHP_P228","rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger","hlc_13Rnd_9x19_JHP_P228"};

        backpack = "B_Kitbag_rgr";

        ALiVE_orbatCreator_loadout[] = {{"hlc_rifle_416D10_st6","hlc_muzzle_556NATO_rotexiiic_grey","rhsusf_acc_anpeq15side_bk","rhsusf_acc_g33_T1",{"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger",30},{},""},{},{"hlc_pistol_P229R_Combat","","","HLC_optic228_VTAC",{"hlc_13Rnd_9x19_JHP_P228",13},{},""},{"U_B_CTRG_Soldier_3_F",{{"ACE_EarPlugs",1},{"ACE_Flashlight_XL50",1},{"ACE_CableTie",5}}},{"V_PlateCarrier1_rgr_noflag_F",{{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",20},{"USP_GPNVG18",1},{"ACE_microDAGR",1},{"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger",8,30},{"hlc_13Rnd_9x19_JHP_P228",1,13},{"SmokeShell",1,1}}},{"B_Kitbag_rgr",{{"ACE_epinephrine",3},{"ACE_morphine",3},{"ACE_packingBandage",20},{"ACE_elasticBandage",20},{"ACE_quikclot",30},{"ACE_salineIV",4},{"ACE_salineIV_500",6},{"ACE_salineIV_250",10},{"ACE_splint",2},{"ACE_tourniquet",6}}},"H_HelmetSpecB","rhs_googles_clear",{"ACE_Vector","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class TAMSF_VSC_TLeader : I_Soldier_TL_F_OCimport_02 {
        editorPreview = \x\\addons\tamsfvsci\data\preview\TAMSF_VSC_TLeader.JPG;
        author = "MSG D.North";
        scope = 2;
        scopeCurator = 2;
        displayName = "Team Leader";
        side = 2;
        faction = "TAMSF_VSC_I";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_HAF_default"};

        uniformClass = "U_B_CTRG_Soldier_3_F";

        linkedItems[] = {"V_PlateCarrier1_rgr_noflag_F","H_HelmetSpecB","ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_PlateCarrier1_rgr_noflag_F","H_HelmetSpecB","ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch"};

        weapons[] = {"hlc_rifle_416D10_st6","hlc_pistol_P229R_Combat","ACE_Vector"};
        respawnWeapons[] = {"hlc_rifle_416D10_st6","hlc_pistol_P229R_Combat","ACE_Vector"};

        magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger","hlc_13Rnd_9x19_JHP_P228","rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger","hlc_13Rnd_9x19_JHP_P228"};
        respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger","hlc_13Rnd_9x19_JHP_P228","rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger","hlc_13Rnd_9x19_JHP_P228"};

        backpack = "B_AssaultPack_rgr";

        ALiVE_orbatCreator_loadout[] = {{"hlc_rifle_416D10_st6","hlc_muzzle_556NATO_rotexiiic_grey","rhsusf_acc_anpeq15side_bk","rhsusf_acc_g33_T1",{"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger",30},{},""},{},{"hlc_pistol_P229R_Combat","","","HLC_optic228_VTAC",{"hlc_13Rnd_9x19_JHP_P228",13},{},""},{"U_B_CTRG_Soldier_3_F",{{"ACE_EarPlugs",1},{"ACE_Flashlight_XL50",1},{"ACE_CableTie",5},{"ACE_tourniquet",2}}},{"V_PlateCarrier1_rgr_noflag_F",{{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",20},{"USP_GPNVG18",1},{"ACE_microDAGR",1},{"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger",8,30},{"hlc_13Rnd_9x19_JHP_P228",1,13},{"SmokeShell",1,1}}},{"B_AssaultPack_rgr",{{"ACE_CableTie",5},{"B_IR_Grenade",3,1},{"SmokeShellGreen",2,1},{"SmokeShell",2,1},{"ACE_CTS9",3,1}}},"H_HelmetSpecB","rhs_googles_clear",{"ACE_Vector","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class TAMSF_VSC_Recon_M107 : I_Soldier_M_F_OCimport_02 {
        editorPreview = \x\\addons\tamsfvsci\data\preview\TAMSF_VSC_Recon_M107.JPG;
        author = "MSG D.North";
        scope = 2;
        scopeCurator = 2;
        displayName = "Recon M107 Marksman";
        side = 2;
        faction = "TAMSF_VSC_I";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_HAF_default"};

        uniformClass = "U_B_CTRG_Soldier_3_F";

        linkedItems[] = {"V_SmershVest_01_radio_F","H_Booniehat_oli","ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_SmershVest_01_radio_F","H_Booniehat_oli","ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_M107_w","hlc_pistol_P229R_Combat","ACE_Vector"};
        respawnWeapons[] = {"rhs_weap_M107_w","hlc_pistol_P229R_Combat","ACE_Vector"};

        magazines[] = {"rhsusf_mag_10Rnd_STD_50BMG_M33","hlc_13Rnd_9x19_JHP_P228","rhsusf_mag_10Rnd_STD_50BMG_M33","hlc_13Rnd_9x19_JHP_P228"};
        respawnMagazines[] = {"rhsusf_mag_10Rnd_STD_50BMG_M33","hlc_13Rnd_9x19_JHP_P228","rhsusf_mag_10Rnd_STD_50BMG_M33","hlc_13Rnd_9x19_JHP_P228"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_M107_w","","","rhsusf_acc_premier",{"rhsusf_mag_10Rnd_STD_50BMG_M33",10},{},""},{},{"hlc_pistol_P229R_Combat","","","HLC_optic228_VTAC",{"hlc_13Rnd_9x19_JHP_P228",13},{},""},{"U_B_CTRG_Soldier_3_F",{{"ACE_EarPlugs",1},{"ACE_Flashlight_XL50",1},{"ACE_CableTie",5},{"ACE_microDAGR",1},{"ACE_tourniquet",2}}},{"V_SmershVest_01_radio_F",{{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",20},{"USP_GPNVG18",1},{"SmokeShell",1,1},{"HandGrenade",1,1},{"rhsusf_mag_10Rnd_STD_50BMG_M33",2,10}}},{},"H_Booniehat_oli","rhs_googles_clear",{"ACE_Vector","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class TAMSF_VSC_Recon_Medic : I_medic_F_OCimport_02 {
        editorPreview = \x\\addons\tamsfvsci\data\preview\TAMSF_VSC_Recon_Medic.JPG;
        author = "MSG D.North";
        scope = 2;
        scopeCurator = 2;
        displayName = "Recon Medic";
        side = 2;
        faction = "TAMSF_VSC_I";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_HAF_default"};

        uniformClass = "U_B_CTRG_Soldier_3_F";

        linkedItems[] = {"V_SmershVest_01_radio_F","H_Booniehat_oli","ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_SmershVest_01_radio_F","H_Booniehat_oli","ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch"};

        weapons[] = {"hlc_rifle_416D10_st6","hlc_pistol_P229R_Combat","ACE_Vector"};
        respawnWeapons[] = {"hlc_rifle_416D10_st6","hlc_pistol_P229R_Combat","ACE_Vector"};

        magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger","hlc_13Rnd_9x19_JHP_P228","rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger","hlc_13Rnd_9x19_JHP_P228"};
        respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger","hlc_13Rnd_9x19_JHP_P228","rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger","hlc_13Rnd_9x19_JHP_P228"};

        backpack = "B_Kitbag_rgr";

        ALiVE_orbatCreator_loadout[] = {{"hlc_rifle_416D10_st6","hlc_muzzle_556NATO_rotexiiic_grey","rhsusf_acc_anpeq15side_bk","rhsusf_acc_g33_T1",{"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger",30},{},""},{},{"hlc_pistol_P229R_Combat","","","HLC_optic228_VTAC",{"hlc_13Rnd_9x19_JHP_P228",13},{},""},{"U_B_CTRG_Soldier_3_F",{{"ACE_EarPlugs",1},{"ACE_Flashlight_XL50",1},{"ACE_CableTie",5},{"ACE_tourniquet",2}}},{"V_SmershVest_01_radio_F",{{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",20},{"USP_GPNVG18",1},{"ACE_microDAGR",1},{"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger",8,30},{"hlc_13Rnd_9x19_JHP_P228",1,13},{"SmokeShell",1,1},{"HandGrenade",1,1}}},{"B_Kitbag_rgr",{{"ACE_epinephrine",3},{"ACE_morphine",3},{"ACE_packingBandage",20},{"ACE_elasticBandage",20},{"ACE_quikclot",30},{"ACE_salineIV",4},{"ACE_salineIV_500",6},{"ACE_salineIV_250",10},{"ACE_splint",2},{"ACE_tourniquet",6}}},"H_Booniehat_oli","rhs_googles_clear",{"ACE_Vector","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class TAMSF_VSC_Recon_SniperM24 : I_Soldier_M_F_OCimport_02 {
        editorPreview = \x\\addons\tamsfvsci\data\preview\TAMSF_VSC_Recon_SniperM24.JPG;
        author = "MSG D.North";
        scope = 2;
        scopeCurator = 2;
        displayName = "Recon Sniper";
        side = 2;
        faction = "TAMSF_VSC_I";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_HAF_default"};

        uniformClass = "U_B_CTRG_Soldier_3_F";

        linkedItems[] = {"V_SmershVest_01_radio_F","H_Booniehat_oli","ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_SmershVest_01_radio_F","H_Booniehat_oli","ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_m24sws_wd","hlc_pistol_P229R_Combat","ACE_Vector"};
        respawnWeapons[] = {"rhs_weap_m24sws_wd","hlc_pistol_P229R_Combat","ACE_Vector"};

        magazines[] = {"rhsusf_5Rnd_762x51_m118_special_Mag","hlc_13Rnd_9x19_JHP_P228","rhsusf_5Rnd_762x51_m118_special_Mag","hlc_13Rnd_9x19_JHP_P228"};
        respawnMagazines[] = {"rhsusf_5Rnd_762x51_m118_special_Mag","hlc_13Rnd_9x19_JHP_P228","rhsusf_5Rnd_762x51_m118_special_Mag","hlc_13Rnd_9x19_JHP_P228"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_m24sws_wd","","","rhsusf_acc_M8541_wd",{"rhsusf_5Rnd_762x51_m118_special_Mag",5},{},""},{},{"hlc_pistol_P229R_Combat","","","HLC_optic228_VTAC",{"hlc_13Rnd_9x19_JHP_P228",13},{},""},{"U_B_CTRG_Soldier_3_F",{{"ACE_EarPlugs",1},{"ACE_Flashlight_XL50",1},{"ACE_CableTie",5},{"ACE_microDAGR",1},{"ACE_tourniquet",2}}},{"V_SmershVest_01_radio_F",{{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",20},{"USP_GPNVG18",1},{"SmokeShell",2,1},{"rhsusf_5Rnd_762x51_m993_Mag",5,5}}},{},"H_Booniehat_oli","rhs_googles_clear",{"ACE_Vector","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class TAMSF_VSC_Recon_Operator : I_soldier_F_OCimport_02 {
        editorPreview = \x\\addons\tamsfvsci\data\preview\TAMSF_VSC_Recon_Operator.JPG;
        author = "MSG D.North";
        scope = 2;
        scopeCurator = 2;
        displayName = "Recon Operator";
        side = 2;
        faction = "TAMSF_VSC_I";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_HAF_default"};

        uniformClass = "U_B_CTRG_Soldier_3_F";

        linkedItems[] = {"V_SmershVest_01_radio_F","H_Booniehat_oli","ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_SmershVest_01_radio_F","H_Booniehat_oli","ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch"};

        weapons[] = {"hlc_rifle_416D10_st6","hlc_pistol_P229R_Combat","ACE_Vector"};
        respawnWeapons[] = {"hlc_rifle_416D10_st6","hlc_pistol_P229R_Combat","ACE_Vector"};

        magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger","hlc_13Rnd_9x19_JHP_P228","rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger","hlc_13Rnd_9x19_JHP_P228"};
        respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger","hlc_13Rnd_9x19_JHP_P228","rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger","hlc_13Rnd_9x19_JHP_P228"};

        ALiVE_orbatCreator_loadout[] = {{"hlc_rifle_416D10_st6","hlc_muzzle_556NATO_rotexiiic_grey","rhsusf_acc_anpeq15side_bk","rhsusf_acc_g33_T1",{"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger",30},{},""},{},{"hlc_pistol_P229R_Combat","","","HLC_optic228_VTAC",{"hlc_13Rnd_9x19_JHP_P228",13},{},""},{"U_B_CTRG_Soldier_3_F",{{"ACE_EarPlugs",1},{"ACE_Flashlight_XL50",1},{"ACE_CableTie",5},{"ACE_tourniquet",2}}},{"V_SmershVest_01_radio_F",{{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",20},{"USP_GPNVG18",1},{"ACE_microDAGR",1},{"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger",8,30},{"hlc_13Rnd_9x19_JHP_P228",1,13},{"SmokeShell",1,1},{"HandGrenade",1,1}}},{},"H_Booniehat_oli","rhs_googles_clear",{"ACE_Vector","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class TAMSF_VSC_SUV_Armed : UK3CB_ADA_I_SUV_Armed_OCimport_02 {
        editorPreview = \x\\addons\tamsfvsci\data\preview\TAMSF_VSC_SUV_Armed.JPG;
        author = "MSG D.North";
        scope = 2;
        scopeCurator = 2;
        displayName = "SUV (Armed)";
        side = 2;
        faction = "TAMSF_VSC_I";
        crew = "TAMSF_VSC_Operator";

        class Turrets : Turrets {
            class GunnerTurret : GunnerTurret { gunnerType = "TAMSF_VSC_Operator"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\UK3CB_Factions\addons\UK3CB_Factions_Vehicles\wheeled\UK3CB_Factions_Vehicles_suv\data\suv_body_co.paa'];_unit setObjectTextureGlobal [1,'\UK3CB_Factions\addons\UK3CB_Factions_Vehicles\wheeled\UK3CB_Factions_Vehicles_suv\data\armoredsuv_body_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Black";

    };

    class TAMSF_VSC_SUV_Armoured : UK3CB_ADC_I_SUV_Armoured_OCimport_02 {
        editorPreview = \x\\addons\tamsfvsci\data\preview\TAMSF_VSC_SUV_Armoured.JPG;
        author = "MSG D.North";
        scope = 2;
        scopeCurator = 2;
        displayName = "SUV (Armoured)";
        side = 2;
        faction = "TAMSF_VSC_I";
        crew = "TAMSF_VSC_Operator";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class TAMSF_VSC_UH1H_Armed : UK3CB_UN_I_UH1H_M240_OCimport_02 {
        editorPreview = \x\\addons\tamsfvsci\data\preview\TAMSF_VSC_UH1H_Armed.JPG;
        author = "MSG D.North";
        scope = 2;
        scopeCurator = 2;
        displayName = "UH-1H (Armed)";
        side = 2;
        faction = "TAMSF_VSC_I";
        crew = "TAMSF_VSC_Operator";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = ""; };
            class RightGunner : RightGunner { gunnerType = "TAMSF_VSC_Operator"; };
            class LeftGunner : LeftGunner { gunnerType = "TAMSF_VSC_Operator"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsgref\addons\rhsgref_air\uh1h\data\uh1h_olv_co.paa'];_unit setObjectTextureGlobal [1,'rhsgref\addons\rhsgref_air\uh1h\data\uh1h_olv_in_co.paa'];_unit setObjectTextureGlobal [2,'rhsgref\addons\rhsgref_air\uh1h\data\mlod_us_co.paa'];_unit setObjectTextureGlobal [3,'rhsgref\addons\rhsgref_air\uh1h\data\decals\blank_ca.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "OLIVE";

    };

};