//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 200.146773 on Stable branch
// Generated with ALiVE version 1.12.1.2002131
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class TAMSF_AWTF_B {
        displayName = "Asymmetric Warfare Task Force";
        side = 1;
        flag = "\a3\Data_f\Flags\flag_nato_co.paa";
        icon = "\a3\Data_f\Flags\flag_nato_co.paa";
        priority = 1;
    };
};