//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 200.146773 on Stable branch
// Generated with ALiVE version 1.12.1.2002131
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups {
    class WEST {

        class TAMSF_AWTF_B {
            name = "Asymmetric Warfare Task Force";

            class Infantry {
                name = "Infantry";

                class TAMSF_AWTF_RifleSquad {
                    name = "Rifle Squad";
                    side = 1;
                    faction = "TAMSF_AWTF_B";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "TAMSF_AWTF_SLeader";
                    };
                    class Unit1 {
                        position[] = {-10,-10,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "TAMSF_AWTF_TLeader";
                    };
                    class Unit2 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "TAMSF_AWTF_Autorifleman";
                    };
                    class Unit3 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "TAMSF_AWTF_Grenadier";
                    };
                    class Unit4 {
                        position[] = {-25,-25,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "TAMSF_AWTF_Rifleman_LAT";
                    };
                    class Unit5 {
                        position[] = {30,-30,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "TAMSF_AWTF_TLeader";
                    };
                    class Unit6 {
                        position[] = {-30,-30,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "TAMSF_AWTF_Autorifleman";
                    };
                    class Unit7 {
                        position[] = {35,-35,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "TAMSF_AWTF_Grenadier";
                    };
                    class Unit8 {
                        position[] = {-35,-35,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "TAMSF_AWTF_Rifleman_LAT";
                    };
                    class Unit9 {
                        position[] = {40,-40,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "TAMSF_AWTF_CMedic";
                    };
                    class Unit10 {
                        position[] = {-40,-40,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "TAMSF_AWTF_CEngineer";
                    };
                };

                class TAMSF_AWTF_FireTeam {
                    name = "Fire Team";
                    side = 1;
                    faction = "TAMSF_AWTF_B";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "TAMSF_AWTF_TLeader";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "TAMSF_AWTF_Autorifleman";
                    };
                    class Unit2 {
                        position[] = {-5,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "TAMSF_AWTF_Grenadier";
                    };
                    class Unit3 {
                        position[] = {10,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "TAMSF_AWTF_Rifleman";
                    };
                };

                class TAMSF_AWTF_ReconSquad {
                    name = "Recon Squad";
                    side = 1;
                    faction = "TAMSF_AWTF_B";
                    icon = "\A3\ui_f\data\map\markers\nato\b_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "TAMSF_AWTF_Recon_TLeader";
                    };
                    class Unit1 {
                        position[] = {-10,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "TAMSF_AWTF_Recon_Rifleman";
                    };
                    class Unit2 {
                        position[] = {10,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "TAMSF_AWTF_Recon_Rifleman_LAT";
                    };
                    class Unit3 {
                        position[] = {-5,-25,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "TAMSF_AWTF_Recon_CMedic";
                    };
                    class Unit4 {
                        position[] = {5,-25,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "TAMSF_AWTF_Recon_JTAC";
                    };
                    class Unit5 {
                        position[] = {0,-30,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "TAMSF_AWTF_Recon_Marksman";
                    };
                };

                class TAMSF_AWTF_PlatoonHQ {
                    name = "Platoon HQ";
                    side = 1;
                    faction = "TAMSF_AWTF_B";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "LIEUTENANT";
                        side = 1;
                        vehicle = "TAMSF_AWTF_PLeader";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "TAMSF_AWTF_PSergeant";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "TAMSF_AWTF_CMedic";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "TAMSF_AWTF_CMedic";
                    };
                };

            };

            class SpecOps {
                name = "SpecOps";

            };

            class Motorized {
                name = "Motorized";

                class TAMSF_AWTF_M1126_M2_Patrol {
                    name = "M1126 (M2) Patrol";
                    side = 1;
                    faction = "TAMSF_AWTF_B";
                    icon = "\A3\ui_f\data\map\markers\nato\b_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "TAMSF_AWTF_M1126_M2";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "TAMSF_AWTF_SLeader";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "TAMSF_AWTF_TLeader";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "TAMSF_AWTF_Autorifleman";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "TAMSF_AWTF_Grenadier";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "TAMSF_AWTF_Rifleman_LAT";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "TAMSF_AWTF_TLeader";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "TAMSF_AWTF_Autorifleman";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "TAMSF_AWTF_Grenadier";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "TAMSF_AWTF_Rifleman";
                    };
                    class Unit10 {
                        position[] = {-25,-25,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "TAMSF_AWTF_CMedic";
                    };
                    class Unit11 {
                        position[] = {30,-30,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "TAMSF_AWTF_CEngineer";
                    };
                };

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support";

            };

            class Mechanized {
                name = "Mechanized";

                class TAMSF_AWTF_M2A3_Platoon {
                    name = "M2A3 Platoon";
                    side = 1;
                    faction = "TAMSF_AWTF_B";
                    icon = "\A3\ui_f\data\map\markers\nato\b_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "TAMS_AWTF_M2A3";
                    };
                    class Unit1 {
                        position[] = {9,-11,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "TAMS_AWTF_M2A3";
                    };
                    class Unit2 {
                        position[] = {-9,-11,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "TAMS_AWTF_M2A3";
                    };
                };

                class TAMSF_AWTF_M2A3_BUSK_III_Platoon {
                    name = "M2A3 (BUSK III) Platoon";
                    side = 1;
                    faction = "TAMSF_AWTF_B";
                    icon = "\A3\ui_f\data\map\markers\nato\b_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "TAMSF_AWTF_M2A3_BUSK_III";
                    };
                    class Unit1 {
                        position[] = {9,-13,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "TAMSF_AWTF_M2A3_BUSK_III";
                    };
                    class Unit2 {
                        position[] = {-9,-13,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "TAMSF_AWTF_M2A3_BUSK_III";
                    };
                };

            };

            class Armored {
                name = "Armored";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

                class TAMSF_AWTF_AirWing {
                    name = "CAB Air Wing";
                    side = 1;
                    faction = "TAMSF_AWTF_B";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "LIEUTENANT";
                        side = 1;
                        vehicle = "TAMSF_AWTF_RotaryPilot";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "LIEUTENANT";
                        side = 1;
                        vehicle = "TAMSF_AWTF_RotaryPilot";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "LIEUTENANT";
                        side = 1;
                        vehicle = "TAMSF_AWTF_RotaryPilot";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "LIEUTENANT";
                        side = 1;
                        vehicle = "TAMSF_AWTF_RotaryPilot";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "LIEUTENANT";
                        side = 1;
                        vehicle = "TAMSF_AWTF_RotaryPilot";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "LIEUTENANT";
                        side = 1;
                        vehicle = "TAMSF_AWTF_RotaryPilot";
                    };
                    class Unit6 {
                        position[] = {20,-20,0};
                        rank = "LIEUTENANT";
                        side = 1;
                        vehicle = "TAMSF_AWTF_A10Pilot";
                    };
                    class Unit7 {
                        position[] = {-15,-25,0};
                        rank = "LIEUTENANT";
                        side = 1;
                        vehicle = "TAMSF_AWTF_A10Pilot";
                    };
                    class Unit8 {
                        position[] = {15,-25,0};
                        rank = "LIEUTENANT";
                        side = 1;
                        vehicle = "TAMSF_AWTF_F16Pilot";
                    };
                    class Unit9 {
                        position[] = {-10,-30,0};
                        rank = "LIEUTENANT";
                        side = 1;
                        vehicle = "TAMSF_AWTF_F16Pilot";
                    };
                };

                class TAMSF_AWTF_AH64D_Wing {
                    name = "AH-64D Wing";
                    side = 1;
                    faction = "TAMSF_AWTF_B";
                    icon = "\A3\ui_f\data\map\markers\nato\b_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "LIEUTENANT";
                        side = 1;
                        vehicle = "TAMSF_AWTF_AH64D";
                    };
                    class Unit1 {
                        position[] = {20,-26,0};
                        rank = "LIEUTENANT";
                        side = 1;
                        vehicle = "TAMSF_AWTF_AH64D";
                    };
                };

                class TAMSF_AWTF_A10C_Flight {
                    name = "A-10C Flight";
                    side = 1;
                    faction = "TAMSF_AWTF_B";
                    icon = "\A3\ui_f\data\map\markers\nato\b_plane.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "LIEUTENANT";
                        side = 1;
                        vehicle = "TAMSF_AWTF_A10C";
                    };
                    class Unit1 {
                        position[] = {26,-24,0};
                        rank = "LIEUTENANT";
                        side = 1;
                        vehicle = "TAMSF_AWTF_A10C";
                    };
                };

                class TAMSF_AWTF_F16C_Flight {
                    name = "F-16C Flight";
                    side = 1;
                    faction = "TAMSF_AWTF_B";
                    icon = "\A3\ui_f\data\map\markers\nato\b_plane.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "LIEUTENANT";
                        side = 1;
                        vehicle = "TAMSF_AWTF_F16C_Fighting_Falcon_Blk25_HTime";
                    };
                    class Unit1 {
                        position[] = {16,-32,0};
                        rank = "LIEUTENANT";
                        side = 1;
                        vehicle = "TAMSF_AWTF_F16C_Fighting_Falcon_Blk25_HTime";
                    };
                };

                class TAMSF_AWTF_CABHQ {
                    name = "CAB HQ";
                    side = 1;
                    faction = "TAMSF_AWTF_B";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CAPTAIN";
                        side = 1;
                        vehicle = "TAMSF_AWTF_Officer";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "LIEUTENANT";
                        side = 1;
                        vehicle = "TAMSF_AWTF_Officer";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "TAMSF_AWTF_FMedic";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "TAMSF_AWTF_FMedic";
                    };
                };
            };
        };
    };
};