//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 200.146773 on Stable branch
// Generated with ALiVE version 1.12.1.2002131
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class TAMSF_VNR_O {
        displayName = "Virojoki People's Republic";
        side = 0;
        flag = "\rhsafrf\addons\rhs_main\data\flag_map\Flag_dnr_CO.paa";
        icon = "\rhsafrf\addons\rhs_main\data\flag_map\Flag_dnr_CO.paa";
        priority = 0;
    };
};