//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 200.146773 on Stable branch
// Generated with ALiVE version 1.12.1.2002131
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups {
    class EAST {

        class TAMSF_VNR_O {
            name = "Virojoki People's Republic";

            class Infantry {
                name = "Infantry";

                class TAMSF_VNR_Separatist_FireTeam {
                    name = "Separatist Fire Team";
                    side = 0;
                    faction = "TAMSF_VNR_O";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TAMSF_VNR_Regulars_TLeader";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Separatist_Gunner";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Separatist_Grenadier";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Separatist_Rifleman";
                    };
                };

                class TAMSF_VNR_Separatist_Patrol {
                    name = "Separatist Patrol";
                    side = 0;
                    faction = "TAMSF_VNR_O";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TAMSF_VNR_Regulars_TLeader";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Separatist_Rifleman";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Separatist_Rifleman";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Separatist_Gunner";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Separatist_Grenadier";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TAMSF_VNR_Separatist_Rifleman";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Separatist_Grenadier";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Separatist_Gunner";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Separatist_Rifleman";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Separatist_Grenadier";
                    };
                };

                class TAMSF_VNR_Regulars_AATeam {
                    name = "Regulars AA Team";
                    side = 0;
                    faction = "TAMSF_VNR_O";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TAMSF_VNR_Regulars_TLeader";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Regulars_Rifleman";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Regulars_Rifleman_AA";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Regulars_Rifleman_AA";
                    };
                };

                class TAMSF_VNR_Regulars_FTeam {
                    name = "Regulars Fire Team";
                    side = 0;
                    faction = "TAMSF_VNR_O";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TAMSF_VNR_Regulars_TLeader";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Regulars_Grenadier";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Regulars_Rifleman_LAT";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Regulars_Rifleman";
                    };
                };

                class TAMSF_VNR_Regulars_Section {
                    name = "Regulars Section";
                    side = 0;
                    faction = "TAMSF_VNR_O";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TAMSF_VNR_Regulars_TLeader";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Regulars_Grenadier";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Regulars_Rifleman";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Regulars_Rifleman_LAT";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Regulars_Grenadier";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Regulars_Rifleman";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Regulars_Rifleman_AA";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Regulars_Grenadier";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Regulars_Rifleman";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Regulars_Rifleman_LAT";
                    };
                };

                class TAMSF_VNR_SeparatistMGSquad {
                    name = "Separatist Gunner Squad";
                    side = 0;
                    faction = "TAMSF_VNR_O";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TAMSF_VNR_Regulars_TLeader";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Separatist_Gunner";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Separatist_Rifleman";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Separatist_Gunner";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Separatist_Rifleman";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Separatist_Gunner";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Separatist_Rifleman";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Separatist_Gunner";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Separatist_Rifleman";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Separatist_Grenadier";
                    };
                    class Unit10 {
                        position[] = {-25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Separatist_Grenadier";
                    };
                };

                class TAMSF_VNR_Separatist_ATSection {
                    name = "Separatist AT Section";
                    side = 0;
                    faction = "TAMSF_VNR_O";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TAMSF_VNR_Regulars_TLeader";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Separatist_Rifleman";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Separatist_Rifleman_LAT";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Separatist_ATRifleman";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Separatist_Rifleman";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Separatist_Grenadier";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Separatist_ATRifleman";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Separatist_Rifleman_LAT";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Separatist_Rifleman";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Separatist_Gunner";
                    };
                };

            };

            class SpecOps {
                name = "SpecOps";

                class TAMSF_VNR_Spetsnaz_Team {
                    name = "Spetsnaz Team";
                    side = 0;
                    faction = "TAMSF_VNR_O";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TAMSF_VNR_Spetsnaz_TLeader";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TAMSF_VNR_Spetsnaz_Grenadier";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Spetsnaz_Operator";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Spetsnaz_Operator";
                    };
                };

            };

            class Motorized {
                name = "Motorized";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support";

                class TAMSF_VNR_Regulars_Mortar {
                    name = "Regulars Mortar Team";
                    side = 0;
                    faction = "TAMSF_VNR_O";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TAMSF_VNR_Regulars_MortarGunner";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_Regulars_MortarAmmo";
                    };
                };

            };

            class Mechanized {
                name = "Mechanized";

            };

            class Armored {
                name = "Armored";

                class TAMSF_VNR_T72_Platoon {
                    name = "T-72 Platoon";
                    side = 0;
                    faction = "TAMSF_VNR_O";
                    icon = "\A3\ui_f\data\map\markers\nato\o_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TAMSF_VNR_T72";
                    };
                    class Unit1 {
                        position[] = {10,-17,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_T72";
                    };
                    class Unit2 {
                        position[] = {-10,-17,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TAMSF_VNR_T72";
                    };
                };

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};